export const SET_TIMERS = "SET_TIMERS";
export const GET_TIMERS = "GET_TIMERS";
export const GET_SELECTEDTIMER = "GET_SELECTEDTIMER";
export const SET_HOURSSELECTEDTIMER = "SET_HOURSSELECTEDTIMER";
export const SET_MINUTESSELECTEDTIMER = "SET_MINUTESSELECTEDTIMER";
export const SET_SECONDSSELECTEDTIMER = "SET_SECONDSSELECTEDTIMER";
